name = "tf2_ros_examples"
description = "Shiny new project"
version = "0.0.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["tf2_ros_examples"]
